language: python
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - if [ $TRAVIS_PYTHON_VERSION == "3.4" ]; then pip install PyYAML==5.2; fi
  - pip install argparse catkin-pkg rosdistro rospkg PyYAML setuptools coverage

script:
  - nosetests --with-coverage

notifications:
  email: false
