language: python
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install argparse catkin-pkg rosdistro rospkg PyYAML setuptools coverage

script:
  - nosetests --with-coverage

notifications:
  email: false
